// https://de1.api.radio-browser.info/json/languages?order=stationcount&reverse=true
export const languages: string[] = [
  "english",
  "spanish",
  "german",
  "french",
  "chinese",
  "russian",
  "italian",
  "greek",
  "polish",
  "portuguese",
  "hindi",
  "dutch",
  "tamil",
  "romanian",
  "arabic",
  "serbian",
  "ukrainian",
  "hungarian",
  "turkish",
  "czech",
  "croatian",
  "japanese",
  "malayalam",
  "filipino",
  "indonesian",
  "swedish",
  "slovak",
  "bosnian",
  "catalan",
  "danish",
  "cantonese",
  "bahasa indonesia",
  "bulgarian",
  "finnish",
  "korean",
  "slovenian",
  "hebrew",
  "persian",
  "thai",
  "swiss german",
  "estonian",
  "norwegian",
  "urdu",
  "swahili",
  "kannada",
  "malay",
  "lithuanian",
  "mandarin",
  "sinhala",
  "macedonian",
  "kazakh",
  "latvian",
  "kurdish",
  "georgian",
  "afrikaans",
  "azerbaijani",
  "amharic",
  "tagalog",
  "belarusian",
  "telugu",
  "vietnamese",
]

export enum LanguageEnum {
  any = "",
  english = "english",
  spanish = "spanish",
  german = "german",
  french = "french",
  chinese = "chinese",
  russian = "russian",
  italian = "italian",
  greek = "greek",
  polish = "polish",
  portuguese = "portuguese",
  hindi = "hindi",
  dutch = "dutch",
  tamil = "tamil",
  romanian = "romanian",
  arabic = "arabic",
  serbian = "serbian",
  ukrainian = "ukrainian",
  hungarian = "hungarian",
  turkish = "turkish",
  czech = "czech",
  croatian = "croatian",
  japanese = "japanese",
  malayalam = "malayalam",
  filipino = "filipino",
  indonesian = "indonesian",
  swedish = "swedish",
  slovak = "slovak",
  bosnian = "bosnian",
  catalan = "catalan",
  danish = "danish",
  cantonese = "cantonese",
  "bahasa indonesia" = "bahasa indonesia",
  bulgarian = "bulgarian",
  finnish = "finnish",
  korean = "korean",
  slovenian = "slovenian",
  hebrew = "hebrew",
  persian = "persian",
  thai = "thai",
  "swiss german" = "swiss german",
  estonian = "estonian",
  norwegian = "norwegian",
  urdu = "urdu",
  swahili = "swahili",
  kannada = "kannada",
  malay = "malay",
  lithuanian = "lithuanian",
  mandarin = "mandarin",
  sinhala = "sinhala",
  macedonian = "macedonian",
  kazakh = "kazakh",
  latvian = "latvian",
  kurdish = "kurdish",
  georgian = "georgian",
  afrikaans = "afrikaans",
  azerbaijani = "azerbaijani",
  amharic = "amharic",
  tagalog = "tagalog",
  belarusian = "belarusian",
  telugu = "telugu",
  vietnamese = "vietnamese",
}
