const BACKEND_ORIGIN = import.meta.env.VITE_BACKEND_ORIGIN
const FRONTEND_ORIGIN = import.meta.env.VITE_FRONTEND_ORIGIN
const MAX_FAVOURITE_STATIONS_ANONYMOUS = import.meta.env
  .VITE_MAX_FAVOURITE_STATIONS_ANONYMOUS
const SUPABASE_PROJECT_URL = import.meta.env.VITE_SUPABASE_PROJECT_URL
const SUPABASE_PUBLIC_KEY = import.meta.env.VITE_SUPABASE_PUBLIC_KEY

export function getEnv() {
  return {
    BACKEND_ORIGIN,
    FRONTEND_ORIGIN,
    MAX_FAVOURITE_STATIONS_ANONYMOUS,
    SUPABASE_PROJECT_URL,
    SUPABASE_PUBLIC_KEY,
  }
}
